package com.enes.hextechsimulator.Database;

import android.app.Activity;
import android.content.SharedPreferences;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;
import android.widget.TextView;

import com.enes.hextechsimulator.ActivityMain;
import com.enes.hextechsimulator.Models.ModelChamp;
import com.enes.hextechsimulator.Models.ModelPlayer;
import com.enes.hextechsimulator.Models.ModelSandik;
import com.enes.hextechsimulator.Models.ModelSkin;
import com.enes.hextechsimulator.Models.ModelSpec;
import com.enes.hextechsimulator.R;
import com.enes.hextechsimulator.RootApp;

import java.util.ArrayList;

public class DatabaseManager {

    private static final boolean DEBUG = true;
    private static final String GUNCEL_YAMA = "9.4-DEBUG"; /* Veritabanı güncellemek için  */
    private static Db db;

    /* Başlangıç değerleri */
    private static final String NAME = "PLAYER";
    private static final int BE = 0;
    private static final int OE = 0;
    private static final int EXP = 0;
    private static final int NEXT_EXP = 200;
    private static final int LEVEL = 1;
    private static final int KEY = 0;


    public static void init() {
        db = Db.getDb();
        initPlayer();
        initItems();
    }

    public static int getBe() {
        return db.daoPlayer().getBe();
    }

    public static void setBe(int be) {
        db.daoPlayer().setBe(be);
    }

    private static void initItems() {
        if (db.daoYama().getAktifYama() != null && DEBUG) {
            Log.e("Veritabanı Versiyonu", db.daoYama().getAktifYama().getYama() + " - Motor Versiyonu:" + GUNCEL_YAMA);
        }
        if (db.daoYama().getAktifYama() == null || !db.daoYama().getAktifYama().getYama().equals(GUNCEL_YAMA)) {
            if (DEBUG) Log.e("Yeni yama bulundu.", "Eski veriler siliniyor.");
            clearAll();
            upgradeDb();
            if (DEBUG) Log.e("Veriler yüklendi.", "Yama versiyonu yükseltiliyor.");
            AktifYama yama = new AktifYama();
            yama.setYama(GUNCEL_YAMA);
            db.daoYama().setAktifYama(yama);
        }
    }

    private static void initPlayer() {
        SharedPreferences sp = RootApp.getContext().getSharedPreferences("Player", Activity.MODE_PRIVATE);
        if (sp.getBoolean("playerDb", true)) {
            if (DEBUG) Log.e("playerDb bulunamadı", "Oyuncu veritabanı yapılandırılıyor.");
            db.daoPlayer().addPlayer(new ModelPlayer(NAME, BE, OE, EXP, NEXT_EXP, LEVEL, KEY));
            sp.edit().putBoolean("playerDb", false).apply();
        }
    }

    private static void upgradeDb() {
        if (DEBUG) Log.e("Veritabanı", "Şampiyonlar yükleniyor...");
        populateChamp();
        if (DEBUG) Log.e("Veritabanı", "Kostümler yükleniyor...");
        populateSkin();
        if (DEBUG) Log.e("Veritabanı", "Sandıklar yükleniyor...");
        populateSandik();
        if (DEBUG) Log.e("Veritabanı", "Spesyaller yükleniyor...");
        populateSpecial();
    }

    private static void clearAll() {
        db.daoChamp().clear();
        db.daoSkin().clear();
        db.daoSandik().clear();
        db.daoYama().clear();
        SQLiteDatabase seq = new SequenceHelper().getDb();
        try {
            seq.execSQL("DELETE FROM 'sqlite_sequence' WHERE name = 'Sampiyonlar'");
            seq.execSQL("DELETE FROM 'sqlite_sequence' WHERE name = 'Kostumler'");
            seq.execSQL("DELETE FROM 'sqlite_sequence' WHERE name = 'Sandiklar'");
            seq.execSQL("DELETE FROM 'sqlite_sequence' WHERE name = 'Specials'");
            seq.execSQL("DELETE FROM 'sqlite_sequence' WHERE name = 'AktifYama'");
        } catch (Exception e) {
            if (DEBUG) Log.e("SeqHelper", "Tablo bulunamadı.");
        }
    }

    private static void populateSpecial() {
        ArrayList<ModelSpec> specialHepsi = new ArrayList<>();
        specialHepsi.add(new ModelSpec(R.string.item_cevher));
        db.daoSpec().addSpecial(specialHepsi);
    }

    private static void populateSandik() {
        ArrayList<ModelSandik> sandiklarHepsi = new ArrayList<>();
        sandiklarHepsi.add(new ModelSandik(R.string.sandik_1, 30, 30, 25, 14, 0.45, 0.45,
                0.10, 1, 1, 5, 25, true, 1, false,
                true, 250, 150));
        sandiklarHepsi.add(new ModelSandik(R.string.sandik_2, 30, 30, 25, 14, 0.45, 0.45,
                0.10, 1, 1, 5, 25, true, 1, false,
                true, 250, 150));
        sandiklarHepsi.add(new ModelSandik(R.string.sandik_3, 30, 30, 25, 14, 0.45, 0.45,
                0.10, 1, 1, 5, 25, true, 1, false,
                true, 250, 150));
        db.daoSandik().addSandik(sandiklarHepsi);
    }

    private static void populateChamp() {
        ArrayList<ModelChamp> samplerHepsi = new ArrayList<>();
        // nadirlik --> 1: 450IP - 2: 1350IP - 3: 3150IP - 4: 4800IP - 5: 6300IP - 6: 7800IP
        samplerHepsi.add(new ModelChamp("Aatrox", 5));
        samplerHepsi.add(new ModelChamp("Ahri", 4));
        samplerHepsi.add(new ModelChamp("Akali", 3));
        samplerHepsi.add(new ModelChamp("Alistar", 2));
        samplerHepsi.add(new ModelChamp("Amumu", 1));
        samplerHepsi.add(new ModelChamp("Anivia", 3));
        samplerHepsi.add(new ModelChamp("Annie", 1));
        samplerHepsi.add(new ModelChamp("Ashe", 1));
        samplerHepsi.add(new ModelChamp("Aurelion Sol", 5));
        samplerHepsi.add(new ModelChamp("Azir", 5));
        samplerHepsi.add(new ModelChamp("Bard", 5));
        samplerHepsi.add(new ModelChamp("Blitzcrank", 3));
        samplerHepsi.add(new ModelChamp("Brand", 4));
        samplerHepsi.add(new ModelChamp("Braum", 5));
        samplerHepsi.add(new ModelChamp("Caitlyn", 4));
        samplerHepsi.add(new ModelChamp("Camille", 5));
        samplerHepsi.add(new ModelChamp("Cassiopeia", 4));
        samplerHepsi.add(new ModelChamp("Cho'Gath", 2));
        samplerHepsi.add(new ModelChamp("Corki", 2));
        samplerHepsi.add(new ModelChamp("Darius", 4));
        samplerHepsi.add(new ModelChamp("Diana", 4));
        samplerHepsi.add(new ModelChamp("Dr.Mundo", 1));
        samplerHepsi.add(new ModelChamp("Draven", 4));
        samplerHepsi.add(new ModelChamp("Ekko", 5));
        samplerHepsi.add(new ModelChamp("Elise", 4));
        samplerHepsi.add(new ModelChamp("Evelynn", 2));
        samplerHepsi.add(new ModelChamp("Ezreal", 4));
        samplerHepsi.add(new ModelChamp("Fiddlesticks", 2));
        samplerHepsi.add(new ModelChamp("Fiora", 4));
        samplerHepsi.add(new ModelChamp("Fizz", 4));
        samplerHepsi.add(new ModelChamp("Galio", 3));
        samplerHepsi.add(new ModelChamp("Gangplank", 3));
        samplerHepsi.add(new ModelChamp("Garen", 1));
        samplerHepsi.add(new ModelChamp("Gnar", 5));
        samplerHepsi.add(new ModelChamp("Gragas", 3));
        samplerHepsi.add(new ModelChamp("Graves", 4));
        samplerHepsi.add(new ModelChamp("Hecarim", 4));
        samplerHepsi.add(new ModelChamp("Heimerdinger", 3));
        samplerHepsi.add(new ModelChamp("Illaoi", 5));
        samplerHepsi.add(new ModelChamp("Irelia", 4));
        samplerHepsi.add(new ModelChamp("Ivern", 5));
        samplerHepsi.add(new ModelChamp("Janna", 2));
        samplerHepsi.add(new ModelChamp("Jarvan IV", 4));
        samplerHepsi.add(new ModelChamp("Jax", 2));
        samplerHepsi.add(new ModelChamp("Jayce", 4));
        samplerHepsi.add(new ModelChamp("Jhin", 5));
        samplerHepsi.add(new ModelChamp("Jinx", 5));
        samplerHepsi.add(new ModelChamp("Kai'Sa", 5));
        samplerHepsi.add(new ModelChamp("Kalista", 5));
        samplerHepsi.add(new ModelChamp("Karma", 3));
        samplerHepsi.add(new ModelChamp("Karthus", 3));
        samplerHepsi.add(new ModelChamp("Kassadin", 3));
        samplerHepsi.add(new ModelChamp("Katarina", 3));
        samplerHepsi.add(new ModelChamp("Kayle", 1));
        samplerHepsi.add(new ModelChamp("Kayn", 5));
        samplerHepsi.add(new ModelChamp("Kennen", 4));
        samplerHepsi.add(new ModelChamp("Kha'Zix", 4));
        samplerHepsi.add(new ModelChamp("Kindred", 5));
        samplerHepsi.add(new ModelChamp("Kled", 5));
        samplerHepsi.add(new ModelChamp("Kog'Maw", 4));
        samplerHepsi.add(new ModelChamp("Le'Blanc", 3));
        samplerHepsi.add(new ModelChamp("Lee Sin", 4));
        samplerHepsi.add(new ModelChamp("Leona", 4));
        samplerHepsi.add(new ModelChamp("Lissandra", 5));
        samplerHepsi.add(new ModelChamp("Lucian", 5));
        samplerHepsi.add(new ModelChamp("Lulu", 4));
        samplerHepsi.add(new ModelChamp("Lux", 3));
        samplerHepsi.add(new ModelChamp("Malphite", 2));
        samplerHepsi.add(new ModelChamp("Malzahar", 4));
        samplerHepsi.add(new ModelChamp("Maokai", 4));
        samplerHepsi.add(new ModelChamp("Master Yi", 1));
        samplerHepsi.add(new ModelChamp("Miss Fortune", 3));
        samplerHepsi.add(new ModelChamp("Mordekaiser", 2));
        samplerHepsi.add(new ModelChamp("Morgana", 2));
        samplerHepsi.add(new ModelChamp("Nami", 4));
        samplerHepsi.add(new ModelChamp("Nasus", 2));
        samplerHepsi.add(new ModelChamp("Nautilus", 4));
        samplerHepsi.add(new ModelChamp("Neeko", 5));
        samplerHepsi.add(new ModelChamp("Nidalee", 3));
        samplerHepsi.add(new ModelChamp("Nocturne", 4));
        samplerHepsi.add(new ModelChamp("Nunu & Willump", 1));
        samplerHepsi.add(new ModelChamp("Olaf", 3));
        samplerHepsi.add(new ModelChamp("Orianna", 4));
        samplerHepsi.add(new ModelChamp("Ornn", 5));
        samplerHepsi.add(new ModelChamp("Pantheon", 3));
        samplerHepsi.add(new ModelChamp("Poppy", 1));
        samplerHepsi.add(new ModelChamp("Pyke", 5));
        samplerHepsi.add(new ModelChamp("Quinn", 4));
        samplerHepsi.add(new ModelChamp("Rakan", 5));
        samplerHepsi.add(new ModelChamp("Rammus", 2));
        samplerHepsi.add(new ModelChamp("Rek'Sai", 5));
        samplerHepsi.add(new ModelChamp("Renekton", 4));
        samplerHepsi.add(new ModelChamp("Rengar", 4));
        samplerHepsi.add(new ModelChamp("Riven", 4));
        samplerHepsi.add(new ModelChamp("Rumble", 4));
        samplerHepsi.add(new ModelChamp("Ryze", 1));
        samplerHepsi.add(new ModelChamp("Sejuani", 4));
        samplerHepsi.add(new ModelChamp("Shaco", 3));
        samplerHepsi.add(new ModelChamp("Shen", 3));
        samplerHepsi.add(new ModelChamp("Shyvana", 3));
        samplerHepsi.add(new ModelChamp("Singed", 1));
        samplerHepsi.add(new ModelChamp("Sion", 2));
        samplerHepsi.add(new ModelChamp("Sivir", 1));
        samplerHepsi.add(new ModelChamp("Skarner", 4));
        samplerHepsi.add(new ModelChamp("Sona", 3));
        samplerHepsi.add(new ModelChamp("Soraka", 1));
        samplerHepsi.add(new ModelChamp("Swain", 4));
        samplerHepsi.add(new ModelChamp("Sylas", 6));
        samplerHepsi.add(new ModelChamp("Syndra", 4));
        samplerHepsi.add(new ModelChamp("Tahm Kench", 5));
        samplerHepsi.add(new ModelChamp("Taliyah", 5));
        samplerHepsi.add(new ModelChamp("Talon", 4));
        samplerHepsi.add(new ModelChamp("Taric", 2));
        samplerHepsi.add(new ModelChamp("Teemo", 2));
        samplerHepsi.add(new ModelChamp("Thresh", 4));
        samplerHepsi.add(new ModelChamp("Tristana", 2));
        samplerHepsi.add(new ModelChamp("Trundle", 4));
        samplerHepsi.add(new ModelChamp("Tryndamare", 2));
        samplerHepsi.add(new ModelChamp("Twisted Fate", 2));
        samplerHepsi.add(new ModelChamp("Twitch", 3));
        samplerHepsi.add(new ModelChamp("Udyr", 2));
        samplerHepsi.add(new ModelChamp("Urgot", 3));
        samplerHepsi.add(new ModelChamp("Varus", 4));
        samplerHepsi.add(new ModelChamp("Vayne", 4));
        samplerHepsi.add(new ModelChamp("Veigar", 2));
        samplerHepsi.add(new ModelChamp("Vel'Koz", 5));
        samplerHepsi.add(new ModelChamp("Vi", 4));
        samplerHepsi.add(new ModelChamp("Viktor", 4));
        samplerHepsi.add(new ModelChamp("Vladimir", 3));
        samplerHepsi.add(new ModelChamp("Volibear", 4));
        samplerHepsi.add(new ModelChamp("Warwick", 1));
        samplerHepsi.add(new ModelChamp("Wukong", 4));
        samplerHepsi.add(new ModelChamp("Xayah", 5));
        samplerHepsi.add(new ModelChamp("Xerath", 4));
        samplerHepsi.add(new ModelChamp("Xin Zhao", 2));
        samplerHepsi.add(new ModelChamp("Yasuo", 5));
        samplerHepsi.add(new ModelChamp("Yorick", 5));
        samplerHepsi.add(new ModelChamp("Zac", 5)); // Fiyatı düsecek yakinda.
        samplerHepsi.add(new ModelChamp("Zed", 4));
        samplerHepsi.add(new ModelChamp("Ziggs", 4));
        samplerHepsi.add(new ModelChamp("Zilean", 2));
        samplerHepsi.add(new ModelChamp("Zoe", 5));
        samplerHepsi.add(new ModelChamp("Zyra", 4));
        db.daoChamp().addChamp(samplerHepsi);
    }

    private static void populateSkin() {
        ArrayList<ModelSkin> kostumlerHepsi = new ArrayList<>();
        // nadirlik --> 1: 750RP - 2: 975RP - 3: 1350RP - 4: 1820RP - 5: 2775RP - 6: 3250RP
        kostumlerHepsi.add(new ModelSkin(1, 0, R.string.aatrox_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 0, R.string.aatrox_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 0, R.string.aatrox_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 0, R.string.aatrox_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 1, R.string.ahri_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 1, R.string.ahri_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 1, R.string.ahri_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 1, R.string.ahri_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 1, R.string.ahri_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 1, R.string.ahri_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 1, R.string.ahri_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 1, R.string.ahri_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 1, R.string.ahri_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 2, R.string.akali_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 2, R.string.akali_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 2, R.string.akali_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 2, R.string.akali_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 2, R.string.akali_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 2, R.string.akali_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 2, R.string.akali_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 2, R.string.akali_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 2, R.string.akali_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 3, R.string.alistar_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 3, R.string.alistar_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 3, R.string.alistar_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 3, R.string.alistar_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 3, R.string.alistar_skin5, 4, true, true));
        kostumlerHepsi.add(new ModelSkin(6, 3, R.string.alistar_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 3, R.string.alistar_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 3, R.string.alistar_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 3, R.string.alistar_skin9, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(10, 3, R.string.alistar_skin10, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 3, R.string.alistar_skin11, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 4, R.string.amumu_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 4, R.string.amumu_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 4, R.string.amumu_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 4, R.string.amumu_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 4, R.string.amumu_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 4, R.string.amumu_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 4, R.string.amumu_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 4, R.string.amumu_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 4, R.string.amumu_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 5, R.string.anivia_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 5, R.string.anivia_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 5, R.string.anivia_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 5, R.string.anivia_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 5, R.string.anivia_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 5, R.string.anivia_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 5, R.string.anivia_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 6, R.string.annie_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 6, R.string.annie_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 6, R.string.annie_skin3, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 6, R.string.annie_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 6, R.string.annie_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 6, R.string.annie_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 6, R.string.annie_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 6, R.string.annie_skin8, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 6, R.string.annie_skin9, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(10, 6, R.string.annie_skin10, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 6, R.string.annie_skin11, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 7, R.string.ashe_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 7, R.string.ashe_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 7, R.string.ashe_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 7, R.string.ashe_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 7, R.string.ashe_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 7, R.string.ashe_skin6, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 7, R.string.ashe_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 7, R.string.ashe_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 7, R.string.ashe_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(10, 7, R.string.ashe_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 8, R.string.aurelion_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 8, R.string.aurelion_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 9, R.string.azir_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 9, R.string.azir_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 9, R.string.azir_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 9, R.string.azir_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 10, R.string.bard_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 10, R.string.bard_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 10, R.string.bard_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 11, R.string.blitzcrank_skin1, 1, true, true));
        kostumlerHepsi.add(new ModelSkin(2, 11, R.string.blitzcrank_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 11, R.string.blitzcrank_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 11, R.string.blitzcrank_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 11, R.string.blitzcrank_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 11, R.string.blitzcrank_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 11, R.string.blitzcrank_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 11, R.string.blitzcrank_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 11, R.string.blitzcrank_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 11, R.string.blitzcrank_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 12, R.string.brand_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 12, R.string.brand_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 12, R.string.brand_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 12, R.string.brand_skin4, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 12, R.string.brand_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 12, R.string.brand_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 13, R.string.braum_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 13, R.string.braum_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 13, R.string.braum_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 13, R.string.braum_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 13, R.string.braum_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 14, R.string.caitlyn_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 14, R.string.caitlyn_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 14, R.string.caitlyn_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 14, R.string.caitlyn_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 14, R.string.caitlyn_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 14, R.string.caitlyn_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 14, R.string.caitlyn_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 14, R.string.caitlyn_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 14, R.string.caitlyn_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 15, R.string.camille_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 15, R.string.camille_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 16, R.string.cass_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 16, R.string.cass_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 16, R.string.cass_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 16, R.string.cass_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 16, R.string.cass_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 17, R.string.cho_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 17, R.string.cho_skin2, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 17, R.string.cho_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 17, R.string.cho_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 17, R.string.cho_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 17, R.string.cho_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 17, R.string.cho_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 18, R.string.corki_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 18, R.string.corki_skin2, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 18, R.string.corki_skin3, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 18, R.string.corki_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 18, R.string.corki_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 18, R.string.corki_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 18, R.string.corki_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 18, R.string.corki_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 19, R.string.darius_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 19, R.string.darius_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 19, R.string.darius_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 19, R.string.darius_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 19, R.string.darius_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 19, R.string.darius_skin6, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 19, R.string.darius_skin7, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 20, R.string.diana_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 20, R.string.diana_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 20, R.string.diana_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 20, R.string.diana_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 20, R.string.diana_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 21, R.string.drmundo_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 21, R.string.drmundo_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 21, R.string.drmundo_skin3, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 21, R.string.drmundo_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 21, R.string.drmundo_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 21, R.string.drmundo_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 21, R.string.drmundo_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 21, R.string.drmundo_skin8, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 21, R.string.drmundo_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 21, R.string.drmundo_skin10, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 22, R.string.draven_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 22, R.string.draven_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 22, R.string.draven_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 22, R.string.draven_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 22, R.string.draven_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 22, R.string.draven_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 22, R.string.draven_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 23, R.string.ekko_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 23, R.string.ekko_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 23, R.string.ekko_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 23, R.string.ekko_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 23, R.string.ekko_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 24, R.string.elise_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 24, R.string.elise_skin2, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(3, 24, R.string.elise_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 24, R.string.elise_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 24, R.string.elise_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 25, R.string.evelynn_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 25, R.string.evelynn_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 25, R.string.evelynn_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 25, R.string.evelynn_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 25, R.string.evelynn_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 25, R.string.evelynn_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 26, R.string.ezreal_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 26, R.string.ezreal_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 26, R.string.ezreal_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 26, R.string.ezreal_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 26, R.string.ezreal_skin5, 6, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 26, R.string.ezreal_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 26, R.string.ezreal_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 26, R.string.ezreal_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 26, R.string.ezreal_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 26, R.string.ezreal_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 26, R.string.ezreal_skin11, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(12, 26, R.string.ezreal_skin12, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 27, R.string.fidd_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 27, R.string.fidd_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 27, R.string.fidd_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 27, R.string.fidd_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 27, R.string.fidd_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 27, R.string.fidd_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 27, R.string.fidd_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 27, R.string.fidd_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 27, R.string.fidd_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 28, R.string.fiora_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 28, R.string.fiora_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 28, R.string.fiora_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 28, R.string.fiora_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 28, R.string.fiora_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 28, R.string.fiora_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 28, R.string.fiora_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 29, R.string.fizz_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 29, R.string.fizz_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 29, R.string.fizz_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 29, R.string.fizz_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 29, R.string.fizz_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 29, R.string.fizz_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 29, R.string.fizz_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 30, R.string.galio_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 30, R.string.galio_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 30, R.string.galio_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 30, R.string.galio_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 30, R.string.galio_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 30, R.string.galio_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 31, R.string.gp_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 31, R.string.gp_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 31, R.string.gp_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 31, R.string.gp_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 31, R.string.gp_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 31, R.string.gp_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 31, R.string.gp_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 31, R.string.gp_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 31, R.string.gp_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 32, R.string.garen_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 32, R.string.garen_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 32, R.string.garen_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 32, R.string.garen_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 32, R.string.garen_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 32, R.string.garen_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 32, R.string.garen_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 32, R.string.garen_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 32, R.string.garen_skin9, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 33, R.string.gnar_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 33, R.string.gnar_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 33, R.string.gnar_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 33, R.string.gnar_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 33, R.string.gnar_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 33, R.string.gnar_skin6, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 34, R.string.gragas_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 34, R.string.gragas_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 34, R.string.gragas_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 34, R.string.gragas_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 34, R.string.gragas_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 34, R.string.gragas_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 34, R.string.gragas_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 34, R.string.gragas_skin8, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 34, R.string.gragas_skin9, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 34, R.string.gragas_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 35, R.string.graves_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 35, R.string.graves_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 35, R.string.graves_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 35, R.string.graves_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 35, R.string.graves_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 35, R.string.graves_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 35, R.string.graves_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 35, R.string.graves_skin8, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(9, 35, R.string.graves_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 36, R.string.hecarim_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 36, R.string.hecarim_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 36, R.string.hecarim_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 36, R.string.hecarim_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 36, R.string.hecarim_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 36, R.string.hecarim_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 36, R.string.hecarim_skin7, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 37, R.string.heimer_skin1, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 37, R.string.heimer_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 37, R.string.heimer_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 37, R.string.heimer_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 37, R.string.heimer_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 37, R.string.heimer_skin6, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 38, R.string.illaoi_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 38, R.string.illaoi_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 39, R.string.irelia_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 39, R.string.irelia_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 39, R.string.irelia_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 39, R.string.irelia_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 39, R.string.irelia_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 39, R.string.irelia_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 40, R.string.ivern_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 41, R.string.janna_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 41, R.string.janna_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 41, R.string.janna_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 41, R.string.janna_skin4, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(5, 41, R.string.janna_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 41, R.string.janna_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 41, R.string.janna_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 41, R.string.janna_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 41, R.string.janna_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 42, R.string.jarvan_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 42, R.string.jarvan_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 42, R.string.jarvan_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 42, R.string.jarvan_skin4, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(5, 42, R.string.jarvan_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 42, R.string.jarvan_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 42, R.string.jarvan_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 42, R.string.jarvan_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 43, R.string.jax_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 43, R.string.jax_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 43, R.string.jax_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 43, R.string.jax_skin4, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(5, 43, R.string.jax_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 43, R.string.jax_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 43, R.string.jax_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 43, R.string.jax_skin8, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 43, R.string.jax_skin9, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 43, R.string.jax_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 44, R.string.jayce_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 44, R.string.jayce_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 44, R.string.jayce_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 44, R.string.jayce_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 45, R.string.jhin_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 45, R.string.jhin_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 45, R.string.jhin_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 45, R.string.jhin_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 46, R.string.jinx_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 46, R.string.jinx_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 46, R.string.jinx_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 46, R.string.jinx_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 46, R.string.jinx_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 46, R.string.jinx_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 47, R.string.kaisa_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 47, R.string.kaisa_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 48, R.string.kalista_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 48, R.string.kalista_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 48, R.string.kalista_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 49, R.string.karma_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 49, R.string.karma_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 49, R.string.karma_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 49, R.string.karma_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 49, R.string.karma_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 49, R.string.karma_skin6, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 49, R.string.karma_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 50, R.string.karthus_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 50, R.string.karthus_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 50, R.string.karthus_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 50, R.string.karthus_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 50, R.string.karthus_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 50, R.string.karthus_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 51, R.string.kassadin_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 51, R.string.kassadin_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 51, R.string.kassadin_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 51, R.string.kassadin_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 51, R.string.kassadin_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 52, R.string.katarina_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 52, R.string.katarina_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 52, R.string.katarina_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 52, R.string.katarina_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 52, R.string.katarina_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 52, R.string.katarina_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 52, R.string.katarina_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 5, R.string.anivia_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 52, R.string.katarina_skin8, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 52, R.string.katarina_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 52, R.string.katarina_skin10, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 53, R.string.kayle_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 53, R.string.kayle_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 53, R.string.kayle_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 53, R.string.kayle_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 53, R.string.kayle_skin5, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(6, 53, R.string.kayle_skin6, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 53, R.string.kayle_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 53, R.string.kayle_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 53, R.string.kayle_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 54, R.string.kayn_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 54, R.string.kayn_skin2, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 55, R.string.kennen_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 55, R.string.kennen_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 55, R.string.kennen_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 55, R.string.kennen_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 55, R.string.kennen_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 55, R.string.kennen_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 55, R.string.kennen_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 56, R.string.kha_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 56, R.string.kha_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 56, R.string.kha_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 56, R.string.kha_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 56, R.string.kha_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 57, R.string.kindred_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 57, R.string.kindred_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 58, R.string.kled_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 58, R.string.kled_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 59, R.string.kog_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 59, R.string.kog_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 59, R.string.kog_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 59, R.string.kog_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 59, R.string.kog_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 59, R.string.kog_skin6, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 59, R.string.kog_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 59, R.string.kog_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 59, R.string.kog_skin9, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 59, R.string.kog_skin10, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 60, R.string.leblanc_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 60, R.string.leblanc_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 60, R.string.leblanc_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 60, R.string.leblanc_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 60, R.string.leblanc_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 60, R.string.leblanc_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 61, R.string.leesin_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 61, R.string.leesin_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 61, R.string.leesin_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 61, R.string.leesin_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 61, R.string.leesin_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 61, R.string.leesin_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 61, R.string.leesin_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 61, R.string.leesin_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 61, R.string.leesin_skin9, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 62, R.string.leona_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 62, R.string.leona_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 62, R.string.leona_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 62, R.string.leona_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 62, R.string.leona_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 62, R.string.leona_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 62, R.string.leona_skin7, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 62, R.string.leona_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 63, R.string.lissandra_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 63, R.string.lissandra_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 63, R.string.lissandra_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 63, R.string.lissandra_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 64, R.string.lucian_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 64, R.string.lucian_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 64, R.string.lucian_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 64, R.string.lucian_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 64, R.string.lucian_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 65, R.string.lulu_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 65, R.string.lulu_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 65, R.string.lulu_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 65, R.string.lulu_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 65, R.string.lulu_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 65, R.string.lulu_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 65, R.string.lulu_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 65, R.string.lulu_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 66, R.string.lux_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 66, R.string.lux_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 66, R.string.lux_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 66, R.string.lux_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 66, R.string.lux_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 66, R.string.lux_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 66, R.string.lux_skin7, 6, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 66, R.string.lux_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 66, R.string.lux_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 67, R.string.malp_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 67, R.string.malp_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 67, R.string.malp_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 67, R.string.malp_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 67, R.string.malp_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 67, R.string.malp_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 67, R.string.malp_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 67, R.string.malp_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 68, R.string.malzahar_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 68, R.string.malzahar_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 68, R.string.malzahar_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 68, R.string.malzahar_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 68, R.string.malzahar_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 68, R.string.malzahar_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 68, R.string.malzahar_skin7, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 69, R.string.maokai_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 69, R.string.maokai_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 69, R.string.maokai_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 69, R.string.maokai_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 69, R.string.maokai_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 69, R.string.maokai_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 69, R.string.maokai_skin7, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(1, 70, R.string.master_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 70, R.string.master_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 70, R.string.master_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 70, R.string.master_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 70, R.string.master_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 70, R.string.master_skin6, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 70, R.string.master_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 70, R.string.master_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 70, R.string.master_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 71, R.string.miss_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 71, R.string.miss_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 71, R.string.miss_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 71, R.string.miss_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 71, R.string.miss_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 71, R.string.miss_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 71, R.string.miss_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 71, R.string.miss_skin8, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 71, R.string.miss_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 71, R.string.miss_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 71, R.string.miss_skin11, 5, false, false));
        kostumlerHepsi.add(new ModelSkin(12, 71, R.string.miss_skin12, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 72, R.string.morde_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 72, R.string.morde_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 72, R.string.morde_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 72, R.string.morde_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 72, R.string.morde_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 73, R.string.morgana_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 73, R.string.morgana_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 73, R.string.morgana_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 73, R.string.morgana_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 73, R.string.morgana_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 73, R.string.morgana_skin6, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(7, 73, R.string.morgana_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 73, R.string.morgana_skin8, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 74, R.string.nami_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 74, R.string.nami_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 74, R.string.nami_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 74, R.string.nami_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 74, R.string.nami_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 74, R.string.nami_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 75, R.string.nasus_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 75, R.string.nasus_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 75, R.string.nasus_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 75, R.string.nasus_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 75, R.string.nasus_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 75, R.string.nasus_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 75, R.string.nasus_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 75, R.string.nasus_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 76, R.string.nautilus_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 76, R.string.nautilus_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 76, R.string.nautilus_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 76, R.string.nautilus_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 76, R.string.nautilus_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 77, R.string.neeko_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 78, R.string.nidalee_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 78, R.string.nidalee_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 78, R.string.nidalee_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 78, R.string.nidalee_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 78, R.string.nidalee_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 78, R.string.nidalee_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 78, R.string.nidalee_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 78, R.string.nidalee_skin8, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 78, R.string.nidalee_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 79, R.string.nocturne_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 79, R.string.nocturne_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 79, R.string.nocturne_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 79, R.string.nocturne_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 79, R.string.nocturne_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 79, R.string.nocturne_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 80, R.string.nunu_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 80, R.string.nunu_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 80, R.string.nunu_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 80, R.string.nunu_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 80, R.string.nunu_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 80, R.string.nunu_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 80, R.string.nunu_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 81, R.string.olaf_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 81, R.string.olaf_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 81, R.string.olaf_skin3, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 81, R.string.olaf_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 81, R.string.olaf_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 81, R.string.olaf_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 81, R.string.olaf_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 82, R.string.orianna_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 82, R.string.orianna_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 82, R.string.orianna_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 82, R.string.orianna_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 82, R.string.orianna_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 82, R.string.orianna_skin6, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 82, R.string.orianna_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 82, R.string.orianna_skin8, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(1, 83, R.string.ornn_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 84, R.string.pantheon_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 84, R.string.pantheon_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 84, R.string.pantheon_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 84, R.string.pantheon_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 84, R.string.pantheon_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 84, R.string.pantheon_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 84, R.string.pantheon_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 84, R.string.pantheon_skin8, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 85, R.string.poppy_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 85, R.string.poppy_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 85, R.string.poppy_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 85, R.string.poppy_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 85, R.string.poppy_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 85, R.string.poppy_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 85, R.string.poppy_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 85, R.string.poppy_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 85, R.string.poppy_skin9, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 86, R.string.pyke_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 86, R.string.pyke_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 87, R.string.quinn_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 87, R.string.quinn_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 87, R.string.quinn_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 87, R.string.quinn_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 88, R.string.rakan_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 88, R.string.rakan_skin2, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 88, R.string.rakan_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 89, R.string.rammus_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 89, R.string.rammus_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 89, R.string.rammus_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 89, R.string.rammus_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 89, R.string.rammus_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 89, R.string.rammus_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 89, R.string.rammus_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 89, R.string.rammus_skin8, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 90, R.string.reksai_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 90, R.string.reksai_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 91, R.string.renekton_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 91, R.string.renekton_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 91, R.string.renekton_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 91, R.string.renekton_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 91, R.string.renekton_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 91, R.string.renekton_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 91, R.string.renekton_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 91, R.string.renekton_skin8, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 91, R.string.renekton_skin9, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 91, R.string.renekton_skin10, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 92, R.string.rengar_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 92, R.string.rengar_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 92, R.string.rengar_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 92, R.string.rengar_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 93, R.string.riven_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 93, R.string.riven_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 93, R.string.riven_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 93, R.string.riven_skin4, 2, false, true));
        kostumlerHepsi.add(new ModelSkin(5, 93, R.string.riven_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 93, R.string.riven_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 93, R.string.riven_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 93, R.string.riven_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 93, R.string.riven_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 94, R.string.rumble_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 94, R.string.rumble_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 94, R.string.rumble_skin3, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 94, R.string.rumble_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 95, R.string.ryze_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 95, R.string.ryze_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 95, R.string.ryze_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 95, R.string.ryze_skin4, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(5, 95, R.string.ryze_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 95, R.string.ryze_skin6, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 95, R.string.ryze_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 95, R.string.ryze_skin8, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 95, R.string.ryze_skin9, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 95, R.string.ryze_skin10, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 96, R.string.sejuani_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 96, R.string.sejuani_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 96, R.string.sejuani_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 96, R.string.sejuani_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 96, R.string.sejuani_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 96, R.string.sejuani_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 96, R.string.sejuani_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 96, R.string.sejuani_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 97, R.string.shaco_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 97, R.string.shaco_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 97, R.string.shaco_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 97, R.string.shaco_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 97, R.string.shaco_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 97, R.string.shaco_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 97, R.string.shaco_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 98, R.string.shen_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 98, R.string.shen_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 98, R.string.shen_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 98, R.string.shen_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 98, R.string.shen_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 98, R.string.shen_skin6, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 98, R.string.shen_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 99, R.string.shyvana_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 99, R.string.shyvana_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 99, R.string.shyvana_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 99, R.string.shyvana_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 99, R.string.shyvana_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 99, R.string.shyvana_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 100, R.string.singed_skin1, 2, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 100, R.string.singed_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 100, R.string.singed_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 100, R.string.singed_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 100, R.string.singed_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 100, R.string.singed_skin6, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 100, R.string.singed_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 100, R.string.singed_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 100, R.string.singed_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 101, R.string.sion_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 101, R.string.sion_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 101, R.string.sion_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 101, R.string.sion_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 101, R.string.sion_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 102, R.string.sivir_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 102, R.string.sivir_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 102, R.string.sivir_skin3, 2, false, true));
        kostumlerHepsi.add(new ModelSkin(4, 102, R.string.sivir_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 102, R.string.sivir_skin5, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(6, 102, R.string.sivir_skin6, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 102, R.string.sivir_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 102, R.string.sivir_skin8, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(9, 102, R.string.sivir_skin9, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(10, 102, R.string.sivir_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 102, R.string.sivir_skin11, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 103, R.string.skarner_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 103, R.string.skarner_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 103, R.string.skarner_skin3, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 103, R.string.skarner_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 104, R.string.sona_skin1, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 104, R.string.sona_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 104, R.string.sona_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 104, R.string.sona_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 104, R.string.sona_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 104, R.string.sona_skin6, 6, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 104, R.string.sona_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 104, R.string.sona_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 105, R.string.soraka_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 105, R.string.soraka_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 105, R.string.soraka_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 105, R.string.soraka_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 105, R.string.soraka_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 105, R.string.soraka_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 105, R.string.soraka_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 105, R.string.soraka_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 105, R.string.soraka_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 106, R.string.swain_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 106, R.string.swain_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 106, R.string.swain_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 106, R.string.swain_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 107, R.string.sylas_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 108, R.string.syndra_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 108, R.string.syndra_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 108, R.string.syndra_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 108, R.string.syndra_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 108, R.string.syndra_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 108, R.string.syndra_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 109, R.string.tahm_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 109, R.string.tahm_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 109, R.string.tahm_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 110, R.string.taliyah_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 110, R.string.taliyah_skin2, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 111, R.string.talon_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 111, R.string.talon_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 111, R.string.talon_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 111, R.string.talon_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 111, R.string.talon_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 111, R.string.talon_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 112, R.string.taric_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 112, R.string.taric_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 112, R.string.taric_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 112, R.string.taric_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 113, R.string.teemo_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 113, R.string.teemo_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 113, R.string.teemo_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 113, R.string.teemo_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 113, R.string.teemo_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 113, R.string.teemo_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 113, R.string.teemo_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 113, R.string.teemo_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 113, R.string.teemo_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(10, 113, R.string.teemo_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 114, R.string.thresh_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 114, R.string.thresh_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 114, R.string.thresh_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 114, R.string.thresh_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 114, R.string.thresh_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 114, R.string.thresh_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 115, R.string.tristana_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 115, R.string.tristana_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 115, R.string.tristana_skin3, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 115, R.string.tristana_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 115, R.string.tristana_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 115, R.string.tristana_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 115, R.string.tristana_skin7, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 115, R.string.tristana_skin8, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 115, R.string.tristana_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 116, R.string.trundle_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 116, R.string.trundle_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 116, R.string.trundle_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 116, R.string.trundle_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 116, R.string.trundle_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 117, R.string.tryn_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 117, R.string.tryn_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 117, R.string.tryn_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 117, R.string.tryn_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 117, R.string.tryn_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 117, R.string.tryn_skin6, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(7, 117, R.string.tryn_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 117, R.string.tryn_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 117, R.string.tryn_skin9, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 118, R.string.twisted_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 118, R.string.twisted_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 118, R.string.twisted_skin3, 4, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 118, R.string.twisted_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 118, R.string.twisted_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 118, R.string.twisted_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 118, R.string.twisted_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 118, R.string.twisted_skin8, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(9, 118, R.string.twisted_skin9, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(10, 118, R.string.twisted_skin10, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(11, 118, R.string.twisted_skin11, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 119, R.string.twitch_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 119, R.string.twitch_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 119, R.string.twitch_skin3, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(4, 119, R.string.twitch_skin4, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 119, R.string.twitch_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 119, R.string.twitch_skin6, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 119, R.string.twitch_skin7, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 119, R.string.twitch_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 119, R.string.twitch_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 120, R.string.udyr_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 120, R.string.udyr_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 120, R.string.udyr_skin3, 6, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 120, R.string.udyr_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 121, R.string.urgot_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 121, R.string.urgot_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 121, R.string.urgot_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 121, R.string.urgot_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 122, R.string.varus_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 122, R.string.varus_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 122, R.string.varus_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 122, R.string.varus_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 122, R.string.varus_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 122, R.string.varus_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 122, R.string.varus_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 123, R.string.vayne_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 123, R.string.vayne_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 123, R.string.vayne_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 123, R.string.vayne_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 123, R.string.vayne_skin5, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 123, R.string.vayne_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 123, R.string.vayne_skin7, 7, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 123, R.string.vayne_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 123, R.string.vayne_skin9, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 124, R.string.veigar_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 124, R.string.veigar_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 124, R.string.veigar_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 124, R.string.veigar_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 124, R.string.veigar_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 124, R.string.veigar_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 124, R.string.veigar_skin7, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(8, 124, R.string.veigar_skin8, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 124, R.string.veigar_skin9, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 125, R.string.velkoz_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 125, R.string.velkoz_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 125, R.string.velkoz_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 126, R.string.vi_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 126, R.string.vi_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 126, R.string.vi_skin3, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 126, R.string.vi_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 126, R.string.vi_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 126, R.string.vi_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 126, R.string.vi_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 127, R.string.viktor_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 127, R.string.viktor_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 127, R.string.viktor_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 127, R.string.viktor_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 128, R.string.vladimir_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 128, R.string.vladimir_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 128, R.string.vladimir_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 128, R.string.vladimir_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 128, R.string.vladimir_skin5, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 128, R.string.vladimir_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 128, R.string.vladimir_skin7, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 128, R.string.vladimir_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 129, R.string.volibear_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 129, R.string.volibear_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 129, R.string.volibear_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 129, R.string.volibear_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 129, R.string.volibear_skin5, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 130, R.string.warwick_skin1, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(2, 130, R.string.warwick_skin2, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(3, 130, R.string.warwick_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 130, R.string.warwick_skin4, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 130, R.string.warwick_skin5, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(6, 130, R.string.warwick_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 130, R.string.warwick_skin7, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 130, R.string.warwick_skin8, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(9, 130, R.string.warwick_skin9, 7, false, true));
        kostumlerHepsi.add(new ModelSkin(10, 130, R.string.warwick_skin10, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 131, R.string.wukong_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 131, R.string.wukong_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 131, R.string.wukong_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 131, R.string.wukong_skin4, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 131, R.string.wukong_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 131, R.string.wukong_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 132, R.string.xayah_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 132, R.string.xayah_skin2, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 132, R.string.xayah_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 133, R.string.xerath_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 133, R.string.xerath_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 133, R.string.xerath_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 133, R.string.xerath_skin4, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 134, R.string.xin_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 134, R.string.xin_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 134, R.string.xin_skin3, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 134, R.string.xin_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 134, R.string.xin_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 134, R.string.xin_skin6, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 134, R.string.xin_skin7, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(8, 134, R.string.xin_skin8, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 135, R.string.yasuo_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 135, R.string.yasuo_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 135, R.string.yasuo_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 135, R.string.yasuo_skin4, 4, false, false));
        kostumlerHepsi.add(new ModelSkin(5, 135, R.string.yasuo_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 136, R.string.yorick_skin1, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 136, R.string.yorick_skin2, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 136, R.string.yorick_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 137, R.string.zac_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 137, R.string.zac_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 137, R.string.zac_skin3, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 138, R.string.zed_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 138, R.string.zed_skin2, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 138, R.string.zed_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 138, R.string.zed_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 138, R.string.zed_skin5, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 139, R.string.ziggs_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 139, R.string.ziggs_skin2, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(3, 139, R.string.ziggs_skin3, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 139, R.string.ziggs_skin4, 2, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 139, R.string.ziggs_skin5, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(6, 139, R.string.ziggs_skin6, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(7, 139, R.string.ziggs_skin7, 3, true, false));
        kostumlerHepsi.add(new ModelSkin(1, 140, R.string.zilean_skin1, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(2, 140, R.string.zilean_skin2, 1, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 140, R.string.zilean_skin3, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(4, 140, R.string.zilean_skin4, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(5, 140, R.string.zilean_skin5, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 141, R.string.zoe_skin1, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 141, R.string.zoe_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(1, 142, R.string.zyra_skin1, 2, false, false));
        kostumlerHepsi.add(new ModelSkin(2, 142, R.string.zyra_skin2, 3, false, false));
        kostumlerHepsi.add(new ModelSkin(3, 142, R.string.zyra_skin3, 1, true, false));
        kostumlerHepsi.add(new ModelSkin(4, 142, R.string.zyra_skin4, 3, false, false));
        db.daoSkin().addSkin(kostumlerHepsi);
    }
}
